### ISSUE TITLE
Date Element specs: fix miscalculation & clarification about leap seconds

### ISSUE THREAD

**Issue by Liisachan** [ietf-wg-cellar/ebml-specification#411] opened 2021-06-19 02:03 UTC
(1) [Date Element](https://github.com/ietf-wg-cellar/ebml-specification/blob/master/specification.markdown#date-element) states:

> This provides a possible expression of time from 1708-09-11T00:12:44.854775808 UTC to 2293-04-11T11:47:16.854775807 UTC.

The correct values should be:
1708-09-11T00:12:44.854775808 wrong
1708-09-22T00:12:43.145224192 correct
2293-04-11T11:47:16.854775807 wrong
2293-04-11T23:47:16.854775807 correct
 (please double-check this)

(2) It also states:

>  the Signed Integer Element that expresses a point in time referenced in nanoseconds from the precise beginning of the third millennium of the Gregorian Calendar in Coordinated Universal Time (also known as 2001-01-01T00:00:00.000000000 UTC)

Every time a leap second is inserted in UTC, an integer defined like above becomes larger by 10^9 than the value naively calculated from the "actual" UTC time. To avoid potential confusion, perhaps one should add "(not counting leap seconds, if any)" after "referenced in nanoseconds" in the definition. For almost all practical purposes, that seems reasonable.

**Comment by robUx4** [comment] 2021-06-20 06:36
1/ how did you come up with these values ? I wouldn't consider the values normative but more informative of the general range it provides (ie "enough").

2/ the leap second is indeed an issue not mentioned. I would assume computer date&time API's take care of that when comparing/adding/substracting dates (not every developer using a date should know when leaps seconds happens or timezones change). So I think the value stored in Matroska should be the value that is the difference between the wanted date and 2001-01-01T00:00:00, leap second shifts included. So it's not the actual number of nanoseconds but a shifted number depending on how many leaps seconds there are. The text should be clarified to reflect that.

**Comment by Liisachan** [comment] 2021-06-20 20:32
Correct me if I'm wrong.

1/ Consider Gregorian years 1701–2300, ignoring leap seconds. The number of nanoseconds in one day is d = 86400*10^9. Similarly, the number of nanoseconds is:
-  In one non-leap year: y = 365d
-  In any consecutive 4 years not including the last year of a century: q = 4y+d
-  In 100 years (20th century): L = 100y + 25d
-  In 100 years (other century): S = 100y + 24d

`MAX_INT64`  is 2^63−1 = 2S + 23q + 100d + 85636854775807, where 2S + 23q means 2 * 100 + 23 * 4 years after 2001-01-01T00:00 i.e. 2293-01-01T00:00. So 100d = (31+28+31+10)d means 2293-04-11, and it's easy to see that 85636854775807 nanoseconds are 23:47:16.854775807. Now, −L − 2S means 1701-01-01T00:00, and `MIN_INT64` = −2^63 = −L − 2S + q + 3y + 265d + 763145224192 means 7 years 265 days after 1701-01-01, or 265 days after 1708-01-01 (leap year) i.e. 1708-09-22. The fraction of day, 763145224192 ns, is 00:12:43.145224192.

2/ Although counting leap seconds may be ideal, doing so requires a lot of non-trivial work, including table-lookup (and the leap-sec table must be constantly updated). Not only that, someone in 2021 can't tell the exact Date value for 2025-01-01T00:00:00 UTC, nor can they decode the Date value 0x0A82C347AF220000 into a human readable string. If, on the other hand, leap seconds are not counted, then 0x0A82C347AF220000 = "2025-01-01T00:00:00 UTC" is deterministic.

**Comment by robUx4** [comment] 2021-06-27 07:19
The value stored in the EBML/Matroska files should be interpreted the same now and in 200 years. Or dates from 17xx should also be interpreted the same no matter what. So the leap seconds have to be taken in consideration (even though a precision of 1s that far is probably not meaningful). If in 200 years there have been many extra leap seconds that old code didn't anticipate they might report dates incorrectly.

The normative definition of the reference of the first nanosecond of the millenium is correct. Other values are informative. Each code has to do their best to account for all time intricacies. I would rather remove the range reference or make it more vague like 
>  This provides a possible expression of time between September 1708 and April 2293.

**Comment by mbunkus** [comment] 2021-06-27 09:49
> The normative definition of the reference of the first nanosecond of the millenium is correct. Other values are informative.

I agree 100%. We're basically using (Unix) Epoch date system, just with nanosecond precision & a slightly different reference (start) date.

This way of storing dates does not concern itself at all with leap seconds, leap years or even time zones. All of those only come into play when converting this value to different systems & representations.

All date systems out there already do conversion between the (Unix) Epoch & human-readable components already, taking leap thingies into account. This is a solved problem.

Date math is very complicated and should not be conflated with this type of storage as it highly depends on the topic in question. For example, when one asks about a person's age the difference in number of years often suffices. If, though, you want to know how much food to shop on Februrary 1st to last until March 1st you will likely want to know the number of days between those two, and that one varies on the year. Next, if you're running a video storage system that uses a set amount of space per second for storage, you might need to be aware of the exact number of seconds (taking leap seconds & leap years into account) between two dates.

>  I would rather remove the range reference or make it more vague like

>> This provides a possible expression of time between September 1708 and April 2293.

That would be fine with me, or be even more vague like "…and roughly April 2293."

**Comment by Liisachan** [comment] 2021-06-27 11:55
Afaik, the (Unix) Epoch date system is usually not counting leap seconds. That's why the Y2038 problem will occur after 2^31−1 <=> 2038-01-19T03:14:07Z. If counting leap seconds, the problem will occur about 30 seconds earlier. Similarly, JavaScript Date(), Windows FILETIME, SYSTEMTIME, etc. are not leap second-aware. Only newer "good" systems are.

How about creating a new 16-byte LeapSecondAwareDate element, besides the legacy 8-byte Date? The current Date element will be problematic anyway if EBML is still used in the 23rd century.

**Comment by mcr** [comment] 2021-06-27 16:39
I'm not sure what you (@Liisachan ) mean.  The Unix epoch counts seconds.  The leap seconds are numbered, but they aren't counted in any special way.  They just are.  It is in the translation to YYYY-MM-DD (in the library) that leap seconds are accounted for.
I can't speak about JavaScript Date() or windows code.  I will be surprised if JavaScript Date() does not take leap seconds into account.

**Comment by Liisachan** [comment] 2021-06-27 17:55
A leap second can be handed, and unambiguously mapped to a specific Unix timestamp, but it is treated specially in the sense that the mapping is not bijective.

Ex. from https://en.wikipedia.org/wiki/Unix_time#Leap_seconds
1998-12-31T23:59:59Z -> 915148799
1998-12-31T23:59:60Z -> 915148800 (essentially not counted)
1999-01-01T00:00:00Z -> 915148800
1999-01-01T00:00:01Z -> 915148801

“Unix time […] is nonlinear with a leap second having the same Unix time as the second before it, and every day is treated as if it contains exactly 86400 seconds.” https://en.wikipedia.org/wiki/Unix_time

**Comment by robUx4** [comment] 2021-07-04 07:27
We don't need to address the time during a leap second, because that time never happened. There is no nanosecond between 1998-12-31T23:59:59.000000000Zand 1999-01-01T00:00:00.000000000Z.

That might need some clarification in the normative description of the Date type. Is it actual nanoseconds that really occurred, not some calendar tricks. Date API's can handle the calendar tricks and usually end up behind able to count time differences. 

EBML Dates should store the difference between the actual UTC date and the beginning of the millennium. I suspect to make things faster libraries usually do the difference with a hardcoded value (libebml and libavformat do). And that is the wrong way to do it. Bypassing date&time API's lose the leap second adjustments.

Since we're supposed to define what exists in the while in this specification, maybe we should express it as a time difference between an integer value representing the date to read/store and a fixed value ?

@JeromeMartinez in your muxer do you use the date&time API's to convert between Matroska and UTC times ? I think archival files are likely more time conscious than how people use Matroska or WebM in general. We only have the `\Segment\Info\DateUTC` date field in Matroska:
> The date and time that the Segment was created by the muxing application or library

For most use case a few leap seconds change in the definition won't make a difference.

**Comment by Liisachan** [comment] 2021-07-04 08:54
> We don't need to address the time during a leap second, because that time never happened. There is no nanosecond between 1998-12-31T23:59:59.000000000Zand 1999-01-01T00:00:00.000000000Z.

Although the above statement is strange, every one of us seems to **agree** on the **same conclusions**:
1) Don't count leap seconds (ignore them). Just like in Unix time, let's treat timestamps as if one day were always 86400 seconds and leap seconds never occurred.
2) For almost all practical purposes, leap seconds are not important anyway.
3) Nevertheless, it may be a good idea to clarify this in the specs just in case, to avoid any potential confusion.

In reality, if there is a leap second, we have 86401 × 10^9 nanoseconds in one day; otherwise 86400 × 10^9 nanoseconds in one day. (So there were 2 SI seconds (2 × 10^9 nanoseconds) between 1998-12-31T23:59:59Z and 1999-01-01T00:00:00Z.) But that is so complicated and unpredictable that maybe nothing good will come out of rigorously leap-sec support, even though counting leap seconds is in principle doable, and might be ideal in theory (e.g. on a TAI-based system).

**Comment by robUx4** [comment] 2021-07-25 06:37
> it may be a good idea to clarify this in the specs just in case, to avoid any potential confusion.

I agree. Since we use a reference, and not the UNIX one, counting how many nanoseconds since that reference, we should tell people if leap seconds have to be counted or not and what to expect from standard API's (ie if they have to do extra work).

**Comment by robUx4** [comment] 2021-07-25 06:43
As for adding a different date format, we should go with a string in a RFC3339 format, which is another well known system and doesn't use a reference that needs to know about leap seconds.

**Comment by Liisachan** [comment] 2021-07-25 23:29
Thanks. As for the comments like...
>  I would rather remove the range reference or make it more vague like
>> "This provides a possible expression of time between September 1708 and April 2293."

and

> That would be fine with me, or be even more vague like "…and roughly April 2293."

...that does make sense, since that information is redundant (just a corollary of the definition).

On the other hand, including the exact limits is informative, and also helpful for testing purposes when someone is writing a parser. If 0x7FFF... and 0x8000... are converted to the strings for these exact moments, the author of the parser will know their code is okay.

BTW I'm new to github. Should I close this because I opened it??

**Comment by robUx4** [comment] 2021-07-26 06:13
I totally forgot I said I'd rather make it vague, I'll update the Pull Request.

You don't need to close the issue. It will be closed when the PR is merged, otherwise I'll do it. As long as it's not merged, the issue is not closed so it shouldn't be closed.

**Closed** 2022-10-30 08:00 UTC
Labels: bug, errata-rfc8794
